remote_theme: just-the-docs/just-the-docs
logo: "/assets/images/Cambridge University Libraries_rev_col.png"
color_scheme: culdp
aux_links:
  "Cambridge University Libraries":
    "https://www.lib.cam.ac.uk/"
  "University of Cambridge":
    "https://www.cam.ac.uk/"
aux_links_new_tab: true
